import { jsPDF } from "jspdf";

export default function ExportButton({ data }) {
  const exportPDF = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const W = 210;
    const margin = 18;
    const lineW = W - margin * 2;
    let y = 20;

    const addText = (text, size, color, bold = false) => {
      doc.setFontSize(size);
      doc.setTextColor(...color);
      if (bold) doc.setFont("helvetica", "bold");
      else doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(text, lineW);
      lines.forEach((line) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, margin, y);
        y += size * 0.45;
      });
      y += 2;
    };

    // Header
    doc.setFillColor(79, 70, 229);
    doc.roundedRect(margin, y - 4, lineW, 18, 3, 3, "F");
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text("📚 StudyMind — Revision Notes", margin + 4, y + 8);
    y += 22;

    // Meta
    addText(`Subject: ${data.subject}`, 10, [148, 163, 184]);
    addText(`Title: ${data.title}`, 10, [148, 163, 184]);
    y += 3;

    // Summary
    addText("Overview", 13, [99, 102, 241], true);
    doc.setDrawColor(99, 102, 241);
    doc.setLineWidth(0.5);
    doc.line(margin, y, margin + lineW, y);
    y += 4;
    addText(data.summary, 10, [71, 85, 105]);
    y += 4;

    // Notes sections
    data.notes.forEach((section) => {
      if (y > 250) { doc.addPage(); y = 20; }
      addText(`${section.emoji}  ${section.heading}`, 12, [99, 102, 241], true);
      section.bullets.forEach((b) => {
        addText(`  • ${b}`, 9.5, [71, 85, 105]);
      });
      y += 3;
    });

    // Key Terms
    if (data.keyTerms?.length) {
      y += 2;
      addText("🔑 Key Terms", 12, [147, 51, 234], true);
      data.keyTerms.forEach(({ term, definition }) => {
        if (y > 260) { doc.addPage(); y = 20; }
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9.5);
        doc.setTextColor(167, 139, 250);
        doc.text(`${term}:`, margin + 2, y);
        const tw = doc.getTextWidth(`${term}: `);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 116, 139);
        const rest = doc.splitTextToSize(definition, lineW - tw - 2);
        doc.text(rest[0] || "", margin + 2 + tw, y);
        y += 5;
        if (rest.length > 1) {
          rest.slice(1).forEach((l) => {
            doc.text(l, margin + 2 + tw, y);
            y += 4.5;
          });
        }
      });
      y += 3;
    }

    // Quiz
    if (data.quiz?.length) {
      doc.addPage();
      y = 20;
      doc.setFillColor(79, 70, 229);
      doc.roundedRect(margin, y - 4, lineW, 18, 3, 3, "F");
      doc.setFontSize(16);
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.text("🎯 Practice Quiz", margin + 4, y + 8);
      y += 22;

      data.quiz.forEach((q, i) => {
        if (y > 240) { doc.addPage(); y = 20; }
        addText(`Q${i + 1}. ${q.question}`, 11, [226, 232, 240], true);
        q.options.forEach((opt, oi) => {
          const isCorrect = oi === q.correctIndex;
          addText(
            `   ${["A", "B", "C", "D"][oi]}. ${opt.replace(/^[A-D]\)\s*/, "")}${isCorrect ? " ✓" : ""}`,
            9.5,
            isCorrect ? [52, 211, 153] : [100, 116, 139]
          );
        });
        addText(`   💡 ${q.explanation}`, 9, [148, 163, 184]);
        y += 3;
      });
    }

    // Footer on all pages
    const totalPages = doc.getNumberOfPages();
    for (let p = 1; p <= totalPages; p++) {
      doc.setPage(p);
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(
        `Generated by StudyMind AI — ${new Date().toLocaleDateString()}   |   Page ${p}/${totalPages}`,
        margin,
        290
      );
    }

    const safeName = data.title.replace(/[^a-z0-9]/gi, "_").slice(0, 40);
    doc.save(`StudyMind_${safeName}.pdf`);
  };

  const exportMarkdown = () => {
    let md = `# 📚 ${data.title}\n\n`;
    md += `**Subject:** ${data.subject}\n\n`;
    md += `## Overview\n${data.summary}\n\n`;

    md += `## Revision Notes\n\n`;
    data.notes.forEach((s) => {
      md += `### ${s.emoji} ${s.heading}\n`;
      s.bullets.forEach((b) => (md += `- ${b}\n`));
      md += "\n";
    });

    if (data.keyTerms?.length) {
      md += `## 🔑 Key Terms\n\n`;
      data.keyTerms.forEach(({ term, definition }) => {
        md += `**${term}** — ${definition}\n\n`;
      });
    }

    if (data.quiz?.length) {
      md += `## 🎯 Practice Quiz\n\n`;
      data.quiz.forEach((q, i) => {
        md += `**Q${i + 1}. ${q.question}**\n\n`;
        q.options.forEach((opt, oi) => {
          const label = ["A", "B", "C", "D"][oi];
          const isCorrect = oi === q.correctIndex;
          md += `${isCorrect ? "✅" : "-"} ${label}. ${opt.replace(/^[A-D]\)\s*/, "")}\n`;
        });
        md += `\n> 💡 ${q.explanation}\n\n---\n\n`;
      });
    }

    md += `*Generated by StudyMind AI — ${new Date().toLocaleDateString()}*\n`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `StudyMind_${data.title.replace(/[^a-z0-9]/gi, "_").slice(0, 40)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex gap-2">
      <button onClick={exportPDF} className="btn-secondary flex items-center gap-1.5">
        <span>📥</span> Export PDF
      </button>
      <button onClick={exportMarkdown} className="btn-secondary flex items-center gap-1.5">
        <span>📋</span> Export Markdown
      </button>
    </div>
  );
}
